-- Write SQL queries to perform the following tasks using the Sakila database:
USE sakila;

-- List the number of films per category.
SELECT c.name AS category, COUNT(f.film_id) AS film_count
FROM category c
JOIN film_category fc ON c.category_id = fc.category_id
JOIN film f ON fc.film_id = f.film_id
GROUP BY c.name
ORDER BY c.name;


-- Retrieve the store ID, city, and country for each store.
SELECT s.store_id, c.city_id, cy.country_id FROM store AS s
JOIN address AS a ON s.address_id = a.address_id
JOIN city AS c ON c.city_id = a.city_id
JOIN country AS cy ON cy.country_id = c.country_id;

-- Calculate the total revenue generated by each store in dollars.
SELECT s.store_id, 
       SUM(p.amount) AS total_revenue
FROM store AS s
JOIN staff AS st ON s.store_id = st.store_id
JOIN payment AS p ON st.staff_id = p.staff_id
GROUP BY s.store_id;

-- Determine the average running time of films for each category.
SELECT c.name AS category_name,
       AVG(f.length) AS average_running_time
FROM film_category AS fc
JOIN film AS f ON fc.film_id = f.film_id
JOIN category AS c ON fc.category_id = c.category_id
GROUP BY c.name;